# Обязательные поля
# Имя задачи на CTFd
name: The meal is served!
# Никнейм в Telegram
author: "@pipline_sh"
# Описание таска на платформе.
description: | 
  `@pipline_sh`

  Ужас! Кафиф растолстел! Диетолог посоветовал ему кушать каждый день диетические голубцы с не жирной рыбкой. Но у Кафифа есть вопрос - а как же правильно варить капусту для голубцов?

category: reverse
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{i_10v3_ripp3d_snAk3s}",
    data: "case_insensitive",
  }

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
   - public/task.zip

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
