# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать 

# Обязательные поля
# Имя задачи на CTFd
name: The lost org
# Никнейм в Telegram
author: "@Deskrejet"
# Описание таска на платформе.
description: | 
  `@Deskrejet`

  Больше трех недель назад пропал один из организаторов. При нем был необходимый нам флаг. Может ты поможешь нам найти пропажу? В последнем своем сообщении он написал нам "51.70402 39.182314". Может это подсказка?
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{h3_wi11_no7_r37urn}",
    data: "case_insensitive",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
tags:
  - osint

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
