# Обязательные поля
# Имя задачи на CTFd
name: We only have paws...
# Никнейм в Telegram
author: "@lumen_02"
# Описание таска на платформе.
description: | 
  `@lumen_02`

  Хоть Кафиф и очень смышлённый кот, навыков вёрстки ему всё же не хватает. Сайт получился довольно кривым, но Кафифа можно понять - у него лапки)

category: web
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

connection_info: https://catlab.tasks.ctf.vrnctf.ru

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnCTF{samAya-blag0RodNaya-p0roDa-koShk3k}",
    data: "case_insensitive",
  }

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
