# Обязательные поля
# Имя задачи на CTFd
name: Fif forgot about his pet
# Никнейм в Telegram
author: "@pipline_sh"
# Описание таска на платформе.
description: | 
  `@pipline_sh`

  В один из дней, Кафиф пошел в магазин за хлебом, забыв дома своего любимого питомца, питона Васю. Вася очень голодный, поможете его накормить? И да,
  Вася обладает очень странным свойством: когда он голоден, то способен отскакивать от стенок своего вольера, и появляться с противоположной стороны. 

category: reverse
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{i_10v3_ripp3d_snAk3s}",
    data: "case_insensitive",
  }

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
   - public/task.zip

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
