# Обязательные поля
# Имя задачи на CTFd
name: Through The Spam
# Никнейм в Telegram
author: "@lumen_02"
# Описание таска на платформе.
description: | 
  `@lumen_02`

  Кафиф в этом году хорошо сдал ЕГЭ и поступил на ФКН ВГУ. Ему нравится наука, но заниматься ей в одиночку довольно скучно. Поэтому Кафиф очень надеется найти единомышленников. Поможете ему?

category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{b3splatn0e_obuch3n1e_cTf}",
    data: "case_insensitive",
  }

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
