# Обязательные поля
# Имя задачи на CTFd
name: Fifs's dusty archives
# Никнейм в Telegram
author: "@pipline_sh"
# Описание таска на платформе.
description: | 
  `@pipline_sh`

  Кафиф вовсе не простой кот! У него дома есть подвал с секретными архивами. Только вот есть одна проблема - он ооочень пыльный! Поможешь разобраться что к чему?

category: reverse
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{l0l_u_cant_f1nd}",
    data: "case_insensitive",
  }

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
   - public/task.zip

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
