# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать 

# Обязательные поля
# Имя задачи на CTFd
name: Siem master
# Никнейм в Telegram
author: "@kotz1k"
# Описание таска на платформе.
description: | 
  `@kotz1k`

  Недавно Кафиф заказал пентест своей инфраструктуры. Пришли результаты, но пентестеры решили не говорить,
  что нашли критическую уязвимость, через которую своровали важные данные. Помогите Кафифу понять, что именно они своровали.

  `kafif:kafif_password`

  P.S. В качестве отправной точки можете взять имя нашего любимца и смотреть все время)
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: joy
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 10
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
connection_info: https://siem.tasks.ctf.vrnctf.ru

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{5pl_c00l_l4n6u463}",
    data: "case_insensitive",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.zip

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"